### ISSUE TITLE
Linux Debian 64 bit

### ISSUE THREAD

**Issue by TG-Philipp** [eXo-OpenSource/ml_pathfind#3]
linux-libs/libstdc++.so.6: version `GLIBCXX_3.4.18' not found

How can I fix it ?

**Comment by jushar** [comment]
If you're on the latest Debian version, try deleting the `linux-libs` folder.

**Comment by TG-Philipp** [comment]
Ist das der /lib Ordner oder wo finde ich diesen?

**Comment by jushar** [comment]
Nein. Der `linux-libs` Ordner im Ordner des MTA-Servers.

**Comment by TG-Philipp** [comment]
Nein funktioniert leider immer noch nicht

MODULE: Unable to load x64/modules/ml_pathfind.so (/...../x64/linux-libs/libstdc++.so.6: version `GLIBCXX_3.4.18' n
ot found (required by /..../x64/modules/ml_pathfind.so))

**Comment by jushar** [comment]
Dann hast du den Ordner noch nicht gelöscht. Laut der Fehlermeldung existiert er noch unter `x64` im MTA-Server Ordner.

**Comment by TG-Philipp** [comment]
Oh Srry es hatte ihn anscheinend nicht ordentlich gelöscht. 
Aber jetzt steht da:
libssl.so.0.9.8: cannot open shared object file: No such file or directory
ERROR: Loading network library (net.so) failed!

**Comment by jushar** [comment]
Welche Distribution (+ Version) verwendest du?

**Comment by TG-Philipp** [comment]
Debian GNU/Linux 8 \n \l

Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07)

**Comment by jushar** [comment]
Ok, the problem is on our side then (see: #4). You can however fix the problem temporally by compiling it yourself.

To do that, please follow the following steps:
1) Download the module's source code: `git clone https://github.com/eXo-MTA/ml_pathfind`
2) Change to the repo dir: `cd ml_pathfind`
3) Generate the Makefiles and start compiling: `./premake5 gmake && cd Build && make config=release_x64`
4) You will find the compiled module library in the `Bin` folder
